// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDiPJQ9-h85XnQ6j1lMPVbkBvRQe3OZ1pQ',
//     appId: '1:654691119096:web:6c104b45170bd1b61bb00d',
//     messagingSenderId: '654691119096',
//     projectId: 'rubia-8772e',
//     authDomain: 'rubia-8772e.firebaseapp.com',
//     databaseURL: 'https://rubia-8772e-default-rtdb.firebaseio.com',
//     storageBucket: 'rubia-8772e.appspot.com',
//     measurementId: 'G-KGKQJ7X7D4',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBnttLjQQdTv-CU4q2CS_ifPh9xrCm-7gc',
//     appId: '1:654691119096:android:52723438e1a691661bb00d',
//     messagingSenderId: '654691119096',
//     projectId: 'rubia-8772e',
//     databaseURL: 'https://rubia-8772e-default-rtdb.firebaseio.com',
//     storageBucket: 'rubia-8772e.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAk2e_5kk67VqZpfqB3IjIUMfs8pJFMnZM',
//     appId: '1:654691119096:ios:59863a661f73acd01bb00d',
//     messagingSenderId: '654691119096',
//     projectId: 'rubia-8772e',
//     databaseURL: 'https://rubia-8772e-default-rtdb.firebaseio.com',
//     storageBucket: 'rubia-8772e.appspot.com',
//     iosBundleId: 'com.example.practices',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAk2e_5kk67VqZpfqB3IjIUMfs8pJFMnZM',
//     appId: '1:654691119096:ios:59863a661f73acd01bb00d',
//     messagingSenderId: '654691119096',
//     projectId: 'rubia-8772e',
//     databaseURL: 'https://rubia-8772e-default-rtdb.firebaseio.com',
//     storageBucket: 'rubia-8772e.appspot.com',
//     iosBundleId: 'com.example.practices',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDiPJQ9-h85XnQ6j1lMPVbkBvRQe3OZ1pQ',
//     appId: '1:654691119096:web:dfcbea86103c8f571bb00d',
//     messagingSenderId: '654691119096',
//     projectId: 'rubia-8772e',
//     authDomain: 'rubia-8772e.firebaseapp.com',
//     databaseURL: 'https://rubia-8772e-default-rtdb.firebaseio.com',
//     storageBucket: 'rubia-8772e.appspot.com',
//     measurementId: 'G-YG681DF4H3',
//   );
// }
